CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	username VARCHAR(32) NOT NULL,
	password VARCHAR(128) NOT NULL,
	email VARCHAR(128) NOT NULL,
	birthday DATE NOT NULL,
	role VARCHAR(5) NOT NULL,
	gender VARCHAR(6) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE review(
	id SERIAL PRIMARY KEY,
	author INTEGER REFERENCES users,
	song INTEGER REFERENCES song,
	rating INTEGER CHECK (rating BETWEEN 1 AND 10),
    comment VARCHAR(2000) DEFAULT '' NOT NULL,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE song(
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    artist VARCHAR(100) NOT NULL,
    album VARCHAR(100),
    genre VARCHAR(50),
    release_date DATE,
    uploaded_by INTEGER REFERENCES users,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)